name: Test E-commerce

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "14"

      - name: Initial state
        run: echo Starting web deployment

      - name: Install dependencies
        run: npm install

      - name: Generate build
        run: npm run build

      - name: Build Success
        run: |
          echo Build is generated successfully
          
      - name: Deploy to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_STAGING_APP_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
            aws s3 ls
      
